#!/bin/bash

# Apply deployments
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml

# Apply service
kubectl apply -f kubeservice.yaml

# List pods
echo "Pods:"
kubectl get pods

# Show logs for green deployment
echo "Logs for green pod:"
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
